/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "matrixOperator.h"


void
matrix_operations_1(char *host)
{
	CLIENT *clnt;
	Output  *result_1;
	Input  add_1_arg;
	Output  *result_2;
	Input  multiply_1_arg;
	Output  *result_3;
	Input  inverse_1_arg;
	Output  *result_4;
	Input  transpose_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATRIX_OPERATIONS, MATRIX_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (Output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = multiply_1(&multiply_1_arg, clnt);
	if (result_2 == (Output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = inverse_1(&inverse_1_arg, clnt);
	if (result_3 == (Output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = transpose_1(&transpose_1_arg, clnt);
	if (result_4 == (Output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	matrix_operations_1 (host);
exit (0);
}
