/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "matrixOperator.h"

Output *add_1_svc(Input *argp, struct svc_req *rqstp)
{
	static Output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Output *multiply_1_svc(Input *argp, struct svc_req *rqstp)
{
	static Output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Output *inverse_1_svc(Input *argp, struct svc_req *rqstp)
{
	static Output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Output *transpose_1_svc(Input *argp, struct svc_req *rqstp)
{
	static Output  result;

	/*
	 * insert server code here
	 */

	return &result;
}
