/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "matrixOperator.h"


void printMatrix(int nrows, int ncols, float* data){

	int currentIndex = 0;
	for(int i = 0; i < nrows; i++){
		for(int j = 0; j < ncols; j++){
			printf("%f ",data[currentIndex++]);
		}
		printf("\n");
	}
}


void matrix_operations_1(char *host, Input input, int id)
{
	CLIENT *clnt;
	Output  *result;
	// Input  add_1_arg;
	// Output  *result_2;
	// Input  multiply_1_arg;
	// Output  *result_3;
	// Input  inverse_1_arg;
	// Output  *result_4;
	// Input  transpose_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATRIX_OPERATIONS, MATRIX_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(id == 1){
		result = add_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.nRows,result->result.nColumns,result->result.data);
		}

	}else if(id == 2){
		result = multiply_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.nRows,result->result.nColumns,result->result.data);
		}		
	}else if(id == 3){

		result = inverse_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.nRows,result->result.nColumns,result->result.data);
		}
	}else{
		result = transpose_1(&input, clnt);
		if (result == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		if(result->errorCode != 0){
			printf("Error: %s\n",result->errorMessage);
		}else{
			printf("Result:\n");
			printMatrix(result->result.nRows,result->result.nColumns,result->result.data);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void getUserInputMatrix(int numberOfRows, int numberOfCols, float* data){
	int currentIndex = 0;
	printf("Enter values for Matrix:\n");
    for (int i = 0; i < numberOfRows; i++) {
        for (int j = 0; j < numberOfCols; j++) {
            scanf("%f", &data[currentIndex++]);
        }
    }
}

int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		host = "localhost";
		// printf ("usage: %s server_host\n", argv[0]);
		// exit (1);
	} else{
		host = argv[1];

	}


	Input input;
	int op_id, nrows, ncols;

	printf("Choose an Operation:\n");
	printf("1.Addition\n2.Multiplication\n3.Inverse\n4.Transpose\nSelect: ");
	scanf("%d", &op_id);

	if(op_id == 1 || op_id == 2){

		input.numOfMatrices = 2;

    	printf("Enter the number of rows: ");
    	scanf("%d", &nrows);
    	printf("Enter the number of columns: ");
    	scanf("%d", &ncols);

    	getUserInputMatrix(nrows,ncols,input.matrices[0].data);
		input.matrices[0].nRows = nrows;
		input.matrices[0].nColumns = ncols;

		getUserInputMatrix(nrows,ncols,input.matrices[1].data);
		input.matrices[1].nRows = nrows;
		input.matrices[1].nColumns = ncols;


	}else if(op_id == 3){

		input.numOfMatrices = 1;

		printf("Enter the order of the matrix: ");
    	scanf("%d", &nrows);

		ncols = nrows;

    	getUserInputMatrix(nrows,ncols,input.matrices[0].data);
		input.matrices[0].nRows = nrows;
		input.matrices[0].nColumns = ncols;

	}else if(op_id == 4){

		input.numOfMatrices = 1;

		printf("Enter the number of rows: ");
    	scanf("%d", &nrows);
    	printf("Enter the number of columns: ");
    	scanf("%d", &ncols);

    	getUserInputMatrix(nrows,ncols,input.matrices[0].data);
		input.matrices[0].nRows = nrows;
		input.matrices[0].nColumns = ncols;

	}else{
		printf("Invalid input\n");
		return -1;
	}

	printf("%d", op_id);

	matrix_operations_1 (host,input,op_id);
exit (0);
}
