/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "matrixOperator.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Matrix *
addition_1(Massage *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, addition,
		(xdrproc_t) xdr_Massage, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
multiplication_1(Massage *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, multiplication,
		(xdrproc_t) xdr_Massage, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
transpose_1(Massage *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, transpose,
		(xdrproc_t) xdr_Massage, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Matrix *
inverse_1(Massage *argp, CLIENT *clnt)
{
	static Matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, inverse,
		(xdrproc_t) xdr_Massage, (caddr_t) argp,
		(xdrproc_t) xdr_Matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
